### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by dkossman** [deanlyoung/homebridge-awair-local#12]
First of all, thanks for publishing this plugin, it seems to work well and exposes the data from my new Awair Element to Homekit.  Much appreciated!

A few enhancement requests:
1. Is it possible to expose the CO2 and air quality metrics directly in the Homekit widgets?  As currently implemented, you need to click into the widget, then click into the Settings to see the actual readings.  

2. It would be great to separate out the air quality data into separate widgets: one for VOC and one for 2.5 ug particulates. (I didn't realize until i enabled the web api that the device reports a 10 ug estimate, not sure how this is done or how valuable it is.)

3. For particulates it would be great to show the actual 2.5 ug/m3 readings rather than the generalized "good" etc values on the widget itself.

4. For CO2 it would be great to show the actual PPM reading on the widget itself

thanks!

**Comment by deanlyoung** [comment]
@dkossman hey! Thank for the feedback/requests. Unfortunately, these are limited by how the Home app works. There might be a third party HomeKit app that can expose those values, but I'm not sure.
