### ISSUE TITLE
Difference between this project and homebridge-awair

### ISSUE THREAD

**Issue by lumaxis** [deanlyoung/homebridge-awair-local#13]
Heya! Apologies if I'm missing anything obvious but how are this project and https://github.com/deanlyoung/homebridge-awair different? The Readmes seem almost identical and I'm having a hard time figuring out what `local` means here.
Thanks!

**Comment by deanlyoung** [comment]
Good question, @lumaxis!
This one uses the optional Local API hosted on-device. Only Awair 2nd Edition, Element, Mint, & Omni are supported at this time.

https://bit.ly/awair-local-api
