### ISSUE TITLE
VOCs can't be displayed in Home app or reported by Siri

### ISSUE THREAD

**Issue by gawtDamn** [deanlyoung/homebridge-awair-local#14]
The label for VOCs that is shown in the Home app is "Volatile Organic Compound Density". This label is too long, as it only allows for the display of the first two digits of the VOC density value (e.g.  "20...") . This is problematic because there's no indication of how many digits are hidden by the ellipses.  Further, on small-screen devices like the original iphone SE and 5s, the ellipses start in the middle of the word "density" and so no information is shown.  Also, it is generally not possible to get Siri to report the value. Asking "what is the volatile organic chemical density in the living room" will work on occasion, so I know that's the right syntax, but it fails 9 times out of ten, preferring to give me the results of a web search. 

Shortening "Volatile Organic Compound Density" to "VOC density" or just "VOC" or "VOC Level" or "V.O.C." so that the label can be displayed along with the value, and so that Siri can recognize a request for and report the value. I just noticed that in the Eve app, this field is labeled VOC Density, so I'm aware it's entirely possible that this is just Apple not testing their code with real data at all, and that VOC Density is a standardized Homekit quantity just like Temperature or Humidity, and you have no ability to change how the Home app displays it or how Siri misidentifies it.

**Comment by deanlyoung** [comment]
Yeah, unfortunately I don't have any control over that through this plug-in. It gives me an idea in our Awair Home app. It could be possible to create a Shortcut in the iOS/iPadOS Shortcuts app with our Developer APIs... 🤔
