### ISSUE TITLE
PM10 / Device Model / Serial

### ISSUE THREAD

**Issue by ghost** [deanlyoung/homebridge-awair-local#2]
Hello! 
Why is there a PM10 value visible on the Air Quality Sensor? Awair does not report this vaue? And it's always 0 :)

My device serial / model / version number is also not picked up from http://x.x.x.x/settings/config/data but i can see the values when browse to the awair webpage

I'am Using the Awair 2nd Edition with frimware 1.0.9

**Comment by deanlyoung** [comment]
Hi @malmentm! The Awair cloud API used to report PM10, so it's more of a legacy bit of code. Wasn't sure if we would ever bring it back, so I left it in here. However, the data is more representative (an internal algorithm based on simulated data), so we didn't want to give people the wrong idea about the veracity of the data. Unless something changes with that internal algorithm (within the sensor itself), it likely will not get exposed again.

As for the device (serial / model / version) values. I would love to add those programmatically! Unfortunately, I haven't done enough testing to get it to populate correctly. I think it's mostly my lack of understanding basic coding concepts than technical feasibility 😅, so if you know anyone who could lend a hand, please by all means.

**Comment by deanlyoung** [comment]
@dmblakeley would you have any insights on how to pull in data to use during the setting up of Services?

**Comment by DMBlakeley** [comment]
To the first comment on PM10 ... The original Awair device reported " aggregated dust". As HomeKit does not have a "dust" characteristic, "PM10" was repurposed in the Awair plugin for reporting "dust". It will be "0" for all other devices. I found myself going in circles as the Awair documentation was inconsistent. The chart shows my findings:
<img width="1092" alt="Awair Air Quality Sensor Services" src="https://user-images.githubusercontent.com/29609206/81617508-9109f780-93b3-11ea-9a78-0a35dfce542d.png">

I am pretty sure that the index.js could be updated to only add the PM10 characteristic to the Air Quality sensor if you have an original Awair device.

I am a bit of a dabbler when it comes to code also but do see that a GET request to:
`http://developer-apis.awair.is/v1/users/self/devices -H 'Authorization: Bearer {developer-token}'` returns in my case:

`{"devices":[{"name":"Awair","macAddress":"708xxx","latitude":41.49397029115807,"preference":"ALLERGY","timezone":"America/New_York","roomType":"BEDROOM","deviceType":"awair-r2","longitude":-82.04209042261311,"spaceType":"HOME","deviceUUID":"awair-r2_1yyyy","deviceId":1yyyy,"locationName":"Somewhere, OH"}]}`

So, an HTTP GET request could be added which would get "name", "macAddress", "deviceType" and "deviceID" from this request and not require these parameters to be part of the config file. I'll see if I can find another example.

**Comment by ghost** [comment]
I also noticed that the VOC level is not showing in the home app. It only says "..." does it work for you?

**Comment by DMBlakeley** [comment]
The HomeKit Air Quality service only displays Excellent -> Poor but not the VOC level directly. The value is there but you need to select the Awair in HomeKit, then Settings (gear in lower right), then "Accessories", then Awair tile, and Settings one more time to see the actual level. 

Yes, a bit crazy as the title (which is also defined by HomeKit) is too long and obscures the value. Haven't figured out if there is any way to change but am reasonably sure that the VOC level cannot be displayed directly as this is a HomeKit "characteristic" and not a "service".

**Comment by ghost** [comment]
Yeah i know. But u cannot se the actual value even if i dig down under settings. It looks like in this screenshot https://images.app.goo.gl/hhcceDGXKeRvy4CA9 but i can only se the "..." three dots :)

**Comment by DMBlakeley** [comment]
I have sorted out the display of PM based on Awair product type. So for an Awair-r2 only "PM2.5 Density" will be shown. "PM10" will only show for an original Awair device as a placeholder for Aggregate Dust as there is not an equivalent HomeKit characteristic. I have not posted this change but can for your to test?

My device serial / model / version number can be picked up in a manner similar to the getData call at line 33 of the index.js file. Would need a slightly different url but would certainly streamline the config file. @deanlyoung do you want me to work on implementing or do you want to take on?

I spent a bunch of time previously trying to figure out how to display VOC and CO2 level previously and concluded that what is displayed in controlled by HomeKit. If anyone knows a workaround (maybe a Custom service) guidance would be appreciated.

**Comment by deanlyoung** [comment]
@DMBlakeley afaik, a Custom Service is what would be used to display individual values, but they would only be available in an app like Eve.

I'd be happy to take a look at the "dust" → "PM10" characteristic branch, but isn't it already supported here: https://github.com/deanlyoung/homebridge-awair/blob/952515bd922d389e11db579364a138ba57eaa680/index.js#L145

Would you mind taking a stab at the device serial / model / version number?

**Comment by DMBlakeley** [comment]
@deanlyoung, I realized that "dust" -> "PM10" was already supported in the code. Probably not clear, I was curious if "dust" could be displayed as the title rather than "PM10". Not a huge deal as this is only for the original Awair device.

I will take a stab at the device serial / model / version number implementation. Will submit a pull request for the refactoring of the PM2_5/PM10 first.

**Comment by DMBlakeley** [comment]
@deanlyoung , I have implemented a getDevice() routine that acquires the "name", "serial", "devType" and "devId" from your Awair user account. This is implemented for a single Awair device in my archive at: https://github.com/DMBlakeley/homebridge-node-alarm-dot-com.

The problem that I am facing as node.js is asynchronous is that getDevice() must run and complete before getData() or getServices() can execute. I have been researching node.js async behavior but this approach does not seem to be the answer as hombridge-awair is running under homebridge. Can you provide any direction/hints on proper approach?

**Comment by deanlyoung** [comment]
@DMBlakeley that sounds like the issue I was having, too. Have you read about `async` and `await`?

https://stackoverflow.com/questions/8775262/synchronous-requests-in-node-js

**Comment by DMBlakeley** [comment]
Yes, I saw that article (as well as many other good articles on `async` and `await`). Now trying to figure out how to implement when using "prototypes" as the "async function" throws an error. A bit of a learning experience! Will keep at it. Regards, Doug

**Comment by DMBlakeley** [comment]
@deanlyoung , I now have a working version which acquires "name", "serial", "devType" and "devId" from your Awair user account using promises. Reformatted as "class" structure which seemed to work better for implementing promises.

This is implemented for a single Awair device in my archive at: https://github.com/DMBlakeley/homebridge-node-alarm-dot-com.

config.schema.json and README.md also updated for compatibility.

Next step to implement for multiple devices based on "name". Any critique fully accepted.

**Comment by DMBlakeley** [comment]
Not quite sure with logging on that I get the initial "error" when initializing the Awair device:

[5/29/2020, 7:27:12 PM] [MyAwair] Initializing Awair accessory...
[5/29/2020, 7:27:12 PM] [MyAwair] [-] getServices completed
[5/29/2020, 7:27:12 PM] [MyAwair] [-] initAwair Error!
[5/29/2020, 7:27:12 PM] [MyAwair] [-] getServices completed

Appears that homebridge tries to registerAccessory immediately which results in this "error". Does not seem to have any impact on operation and the Awair device is initiated correctly with the correct air quality parameters (previous update which I did). Do not like having unexplained errors ...

**Comment by deanlyoung** [comment]
@DMBlakeley looks more organized at least!

Here is an example of a thorough Homebridge plugin I've seen, although it's a Platform plugin vs. Accessory plugin: https://github.com/plasticrake/homebridge-tplink-smarthome

**Comment by DMBlakeley** [comment]
Just saw your 4.6.0 release adding awair-aqi in air_quality_method. Will take a look at the reference you provided.

**Comment by DMBlakeley** [comment]
I have incorporated your 4.6.0 release as well as added code to handle more than 1 Awair device (I cannot test as I only have 1 device).

I have figured out the reason for the getServices initializing errors which I reported above. Awair is implemented as an Accessory and as such the getServices routine will always run first even though information from the getDevices routine is needed first. Once getServices runs, the Awair service cannot be updated. See: https://github.com/homebridge/homebridge/issues/2590

To address, Awair needs to be refactored as a dynamic platform. The Awair accessory can then be added and updated. Wondering if you have looked setting up Awair as a platform? I have found a couple of reference plug-ins and have started the conversion but did not want to reinvent the wheel if you have already been down this path.

You could of course argue that this is a lot of effort for minimal simplification of the config.json file but could provide hooks for addition of other Awair accessories.

(I now see via LinkedIn that you are the Director of Product Management at Awair.)

**Comment by deanlyoung** [comment]
Wow, good find! I had a feeling that it being an Accessory was an issue, and I've always wanted to look into refactoring / porting it over, but I just hadn't had the time. As a platform, it could simply make setup / discovery easier rather than needing so many fields in the config.json. As the most basic implementation, I dreamed of making it as simple as including a list of adding a token (as the only required setting), and for the Local version, doing some kind of network discovery mechanism for all LAN Awair devices (that simple).

edit: also continuing to support the optional fields is kind of nice, too.

**Comment by DMBlakeley** [comment]
I believe that the simplification (with options) you envision is possible. Will keep progressing and see where I get to.

**Comment by deanlyoung** [comment]
Amazing insights, by the way! You've uncovered more in a few than I have in a long time 😅

**Comment by DMBlakeley** [comment]
Dean, thanks for the positive feedback! I am starting to look further into configuring as a Platform. Noticed that night reports are stopping come the end of June. Are there any other planned changes in the Awair API which I should be aware of? Regards, Doug

**Comment by deanlyoung** [comment]
I'm unsure what you mean by "night reports", is that Sleep Report? We don't expose it via the Developer APIs at the moment, and are in the process of consolidating features. No planned changes to the Developer APIs though. There will be new Organization / Enterprise endpoints and functionality, but the Hobbyist endpoints will remain unaffected.

**Comment by DMBlakeley** [comment]
Yes, "Sleep Reports". Should have used correct terminology. Thanks for the additional clarification that Hobbyist endpoints will remain unchanged.

**Comment by deanlyoung** [comment]
PM10 (estimated) is now available via Local Sensors.

**Comment by DMBlakeley** [comment]
Dean, as you might have guessed programming and homebridge is a bit of a hobby for me. I started investigating setting up a dynamic platform in homebridge but found that the documentation was making use of TypeScript so I diverted to get familiar with TS. Now working on refactoring the Awair plugin to be a dynamic platofrm and in TypeScript format. 

The next logical step would be to look at using the Local Sensors directly as this eliminates the internet requests and associated Tier Quotas but requires local implementation of averaging algorithms and sampling. Not sure if this is a first step for you guys to add native HomeKit to Awair.

Regards, Doug

**Comment by deanlyoung** [comment]
It's a hobby here for me as well. I've been enjoying learning by doing and from following folks like you 😊

Native support would be cool, but not a priority at the moment.

**Comment by DMBlakeley** [comment]
Dean, 
After quite a bit of learning and review of published Homebridge templates and Homebridge dynamic platform plug-ins I now have a working version. Still working out GitHub and npm publishing (which is new to me) but I do have the plug-in working locally at my place with the Awair R2 device which I have.

The plugin is posted at: https://github.com/DMBlakeley/homebridge-awair2

The key advantage of this approach is that your Awair devices are learned from your Awair account and information is required in the config.json file. I made the assumption that the remaining config values are common to all of your Awair devices. Approach seemed a reasonable assumption as your were either a "user" or an "org" and in a given environment common settings would seem appropriate. If your were an "org" with different areas the "###" could be different for each area.

Appreciate any feedback you may have. Would also like to find a way to test multiple devices to see if the code really works.
Regards,
Doug

**Comment by deanlyoung** [comment]
@DMBlakeley wow! Amazing! I started reading through the code and it looks great. I have some modifications I can add via a Pull Request. One that comes to mind is intentionally removing devices with an exclusion list in the config file. Because this is a Platform and the devices would be cached now, would you have to re-initialize or go through extra steps to remove the excluded devices if they were previously added?

I love the switch to TypeScript. I've been meaning to look into working with it.

**Comment by DMBlakeley** [comment]
@deanlyoung, glad that you like the shift to TypeScript!

I have just pushed v5.1.0 to npm which has numerous update mainly to address handling of config default values (that are not entered). You will note that the config.shema.json file only has a single REQUIRED entry that being the developer token. Others are under an optional menu.

You ask a good question about intentionally removing devices. The cache is based on the serial numbers of the devices that you have added. I believe if you remove a device from your account the badAccessories logic (line 98, index.ts) should remove the device as the serial number is not found. I know when I made some changes to the code I had to manually remove my Awair accessory through the config-ui-x Homebridge settings menu. As you probably have access to 

I would certainly welcome any modifications that you may suggest. I will say that TS has been a learning experience and a lot of trial and error!

**Comment by DMBlakeley** [comment]
Ok, just one more change, pushed v5.1.1 to nom. I wasn't happy with the way that config.json default values were being handled. Will keep my hands off until you have time to look over from your perspective.
