### ISSUE TITLE
Latest Version Broken: ReferenceError: w is not defined

### ISSUE THREAD

**Issue by swamplynx** [deanlyoung/homebridge-awair-local#3]
Hi,
The latest local version appears to be broken. I am getting the error below and no data into HomeKit. I've verified the local endpoint is still accessible.

[3/18/2020, 10:52:19 AM] [Cafe Awair] [awair-element_994] url: http://192.168.123.68/air-data/latest
[3/18/2020, 10:52:19 AM] [Cafe Awair] [awair-element_994] ReferenceError: w is not defined

Here is my config:

        {
            "accessory": "AwairLocal",
            "name": "Cafe Awair",
            "ip": "192.168.123.68",
            "model": "Awair Element",
            "devType": "awair-r2",
            "devId": "994",
            "serial": "awair-element_994",
            "carbonDioxideThreshold": 1900,
            "carbonDioxideThresholdOff": 1000,
            "air_quality_method": "awair-score",
            "polling_interval": 10,
            "logging": true
        },

**Comment by ghost** [comment]
Samme error for me

**Comment by deanlyoung** [comment]
Found the bug. I will update it in just a minute.

**Comment by deanlyoung** [comment]
Should be fixed with V1.1.3
