### ISSUE TITLE
SyntaxError after update to 1.2.7

### ISSUE THREAD

**Issue by philippgerard** [deanlyoung/homebridge-awair-local#9]
Hi there,

I just updated from 1.2.1 to 1.2.7 and now get this error on bootup of my hoobs (v.3.2.6 on node 12.16.3) instance:

`7/27/2020, 12:06:40 AM Error loading plugin "homebridge-awair-local".7/27/2020, 12:06:40 AM /home/hoobs/.hoobs/node_modules/homebridge-awair-local/index.js:302
			.setCharacteristic(Characteristic.PM10Density, "--");`

`SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Plugin.load (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/plugin.js:44:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:24
    at Array.forEach (<anonymous>)`

My configuration for Awair looks like this:

`    "accessories": [
        {
            "accessory": "AwairLocal",
            "name": "Awair 2nd Edition",
            "ip": "192.168.178.24",
            "manufacturer": "Awair",
            "devType": "awair",
            "devId": "awair-r2_15862",
            "serial": "70886B13049C",
            "model": "Awair-r2",
            "carbonDioxideThreshold": 1200,
            "carbonDioxideThresholdOff": 1200,
            "voc_mixture_mw": 72.6657827301974,
            "air_quality_method": "awair-score",
            "polling_interval": 10,
            "limit": 12,
            "logging": false,
            "plugin_map": {
                "plugin_name": "homebridge-awair-local",
                "index": 0
            },
            "logging_level": 0
        }
    ],`

**Comment by derekpcollins** [comment]
I'm seeing a similar error on v1.2.7.

**Comment by swamplynx** [comment]
Same issue for me.

**Comment by deanlyoung** [comment]
Sorry about that everyone. Thanks for finding the issue and creating a PR!
